// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1591.DeepSpace2019.subsystems;


import org.usfirst.frc1591.DeepSpace2019.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
import java.util.ArrayList;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.AnalogInput;
import edu.wpi.first.wpilibj.drive.MecanumDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class driveTrain extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private WPI_TalonSRX lFmotor;
    private WPI_TalonSRX rFmotor;
    private WPI_TalonSRX rBmotor;
    private WPI_TalonSRX lBmotor;
    private MecanumDrive mecanumDrive;
    private AnalogInput utrasonic;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public ArrayList<Double> Angles = new ArrayList<Double>();

    public driveTrain() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        lFmotor = new WPI_TalonSRX(0);
        
        
        
        rFmotor = new WPI_TalonSRX(1);
        
        
        
        rBmotor = new WPI_TalonSRX(2);
        
        
        
        lBmotor = new WPI_TalonSRX(3);
        
        
        
        mecanumDrive = new MecanumDrive(lFmotor, rFmotor,
              lBmotor, rBmotor);
        addChild("mecanumDrive",mecanumDrive);
        mecanumDrive.setSafetyEnabled(true);
        mecanumDrive.setExpiration(0.1);
        mecanumDrive.setMaxOutput(1.0);

        
        utrasonic = new AnalogInput(0);
        addChild("utrasonic",utrasonic);
        
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

    //even index = right angles
    //odd index = rocket angles
    Angles.add(0.0); //0
    Angles.add(28.75); //1
    Angles.add(90.0); //2
    Angles.add(151.25); //3
    Angles.add(180.0); //4
    Angles.add(-151.25); //5
    Angles.add(-90.0); //6
    Angles.add(-28.75); //7

    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
            
        // Set the default command for a subsystem here.
        setDefaultCommand(new driveManual());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void fieldDrive(double strafe, double vertical, double rotation, double gyroDeg){
        mecanumDrive.driveCartesian(strafe, vertical, rotation / 3, gyroDeg);
    }

    public void slowfieldDrive(double strafe, double vertical, double rotation, double gyroDeg){
        mecanumDrive.driveCartesian(strafe / 2, vertical / 2, rotation / 3, gyroDeg);
    }

    public void timedDrive(double speed, double direction, double rotation){
        mecanumDrive.drivePolar(speed, direction, rotation);
    }

    public void movingRotation(double strafe, double vertical, double rotation, double gyroDeg){
        mecanumDrive.driveCartesian(strafe, vertical, rotation, gyroDeg);
    }

    // watch for changing rotation divisor and slow speed divisors
}

