// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1591.DeepSpace2019.subsystems;


import org.usfirst.frc1591.DeepSpace2019.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class elevator extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private DigitalInput elevatorTopSwitch;
    private DigitalInput elevatorBottomSwitch;
    private Spark elevatorMotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    final int ELEVATOR_UP_SPEED = 1;
    final int ELEVATOR_DOWN_SPEED = -1;

    public elevator() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        elevatorTopSwitch = new DigitalInput(0);
        addChild("elevatorTopSwitch",elevatorTopSwitch);
        
        
        elevatorBottomSwitch = new DigitalInput(1);
        addChild("elevatorBottomSwitch",elevatorBottomSwitch);
        
        
        elevatorMotor = new Spark(1);
        addChild("elevatorMotor",elevatorMotor);
        elevatorMotor.setInverted(false);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        
        //Add elevator switches to smart dashboard
        SmartDashboard.putData("elevatorTopSwitch", elevatorTopSwitch);
        SmartDashboard.putData("elevatorBottomSwitch", elevatorBottomSwitch);
        SmartDashboard.putData("elevatorMotor", elevatorMotor);
    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // This code is run every loop

    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    //move elevator to the top
    public void elevatorTop() { //make this while held so loop doesn't continue
        if (elevatorTopSwitch.get() == true){ //if the top switch is not pressed
            elevatorMotor.set(ELEVATOR_UP_SPEED); //spin motor to move elevator up HOW FAST AND WHAT DIRECTION
        }
        elevatorLimit();
    }

    //move elevator to the bottom
    public void elevatorBottom(){ //make thie while held so loop doesn't continue 
        if (elevatorBottomSwitch.get() == true) { //if the bottom switch is not pressed
            elevatorMotor.set(ELEVATOR_DOWN_SPEED); //spin motor to move elevator down HOW FAST AND WHAT DIRECTION
        }
        elevatorLimit();
    }

    public void elevatorLimit(){
        while(elevatorMotor.get() != 0) { //while the motor is in motion
            if (elevatorTopSwitch.get() == false || elevatorBottomSwitch.get() == false) { // if the either switch is pushed in
                elevatorMotor.set(0); //stop the motor
            }
        }
    }

    //called when an elevator command is interrupted or ended
    public void stop(){
        elevatorMotor.set(0);
    }
}

